services:
  - type: web
    name: bms-boss
    runtime: python
    region: ohio
    plan: free
    rootDir: extraction-service
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.11
